    <v-card>
      <v-card-title>Add New Project</v-card-title>
    </v-card>
      <v-card-text>
        <v-form class="px-3">
            
        </v-form>
      </v-card-text>
  methods: {
    submit() {
      console.log(this.title, this.content)
    },
  },
  methods: {
    submit() {
      console.log(this.title, this.content)
    },
  },
  methods: {
    submit() {
      console.log(this.title, this.content)
    },
  },
  methods: {
    submit() {
      console.log(this.title, this.content)
    },
  },
  methods: {
    submit() {
